openapi: 3.0.3
info:
  title: Interoperability APIs - JWKs
  x-logo:
    url: 'https://spdci.github.io/api-documentation/draft/dci-logo.png'
    backgroundColor: '#FFFFFF'
    altText: Digital Convergence Initiative
  description: Provide JSON Web Key Set to registered clients/services.
  version: 1.0.0
  contact:
    name: DCI Social Protection
    email: info@spdci.org
  license:
    name: DCI Social Protection License
    url: 'https://github.com/spdci/standards/blob/draft/LICENSE.md'
servers:
  - url: 'https://sandbox.spdci.org/namespace/v1.0.0'
    description: Sandbox Server
paths:
  /.well-known/jwks.json:
    get:
      summary: 'JWKs : /.well-known/jwks.json'
      description: This end point is in compliance with IETF RFC 7517 to share the encryption & signature verification public keys over HTTPS channel
      operationId: get_jwks_json
      parameters:
        - $ref: '#/components/parameters/accept-language'
        - $ref: '#/components/parameters/timestamp'
        - $ref: '#/components/parameters/message_id_hdr'
      responses:
        '200':
          description: JSON Web Key Set Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONWebKeySetResponse'
        '404':
          $ref: '#/components/responses/HttpErrorResponse'
        '500':
          $ref: '#/components/responses/HttpErrorResponse'
      deprecated: false
components:
  schemas:
    JSONWebKeySetResponse:
      type: object
      properties:
        keys:
          description: An array of public JWKs used for encryption & verification
          type: array
          items:
            $ref: '#/components/schemas/JSONWebKey'
      required:
        - keys
      description: JSON Web Key Set
    JSONWebKey:
      type: object
      properties:
        kty:
          description: The cryptographic algorithm family used with the key
          type: string
        kid:
          description: The thumbprint of the key according to rfc 7638 which will be used to match a JWS or JWE 'kid' Header Parameter value
          type: string
        use:
          description: The intended use of the key
          type: string
        alg:
          description: Identify the algorithm intented for use with the key
          type: string
      required:
        - kty
        - kid
        - use
        - alg
      description: JSON Web Key Set
  parameters:
    accept-language:
      in: header
      name: accept-language
      description: 'Default value: en'
      required: false
      schema:
        type: string
        example: en
    timestamp:
      in: header
      name: timestamp
      description: 'request timestamp in HTTP Date format - Tue, 06 Mar 2020 21:00:00 GMT'
      required: true
      schema:
        type: string
        example: 'Tue, 06 Mar 2020 21:00:00 GMT'
    message_id_hdr:
      in: header
      name: message_id
      description: Unique message id to communicate between sender and receiver systems and it's scope is restricted to transport layer only to successfully devier the message between sender and receiver.
      schema:
        type: string
        example: '123456789020211216223812'
  responses:
    HttpErrorResponse:
      description: HTTP layer error details
      content:
        application/json:
          schema:
            type: object
            description: 'HTTP transport layer error codes. Used by components like gateways, LB responding with HTTP status codes 1xx, 2xx, 3xx, 4xx and 5xx'
            properties:
              errors:
                items:
                  type: object
                  properties:
                    code:
                      type: string
                      description: error code
                    message:
                      type: string
                      description: error message
